services:

  dogs_db:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: ../
    restart: always
    volumes:
      - static_value:/app/staticfiles/
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - dogs_db
    env_file:
      - .env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/staticfiles/
    env_file:
      - .env

volumes:
  postgres_data:
  static_value: